### ISSUE TITLE
Adaptación a moodle 3.0

### ISSUE THREAD

**Issue by joadelvia** [evalfor/moodle-block_evalcomix#1]
Me encantaría seguir utilizando este magnífico plugin en moodle 3.0

**Comment by evalfor** [comment]
Gracias por usar EvalCOMIX, me alegra saberlo. Dentro de poco comenzaré con las adaptaciones para Moodle 3.0

**Comment by joadelvia** [comment]
He conseguido hacerlo funcionar con la última versión de moodle añadiendo la siguiente línea la fichero version.php:
$plugin->component = 'block_evalcomix';

Quedando el fichero version.php:
<?php
/**
 * @package    block_evalcomix
 * @copyright  2010 onwards EVALfor Research Group {@link http://evalfor.net/}
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @author     Daniel Cabeza Sánchez <daniel.cabeza@uca.es>, Juan Antonio Caballero Hernández <juanantonio.caballero@uca.es>
 */
	$plugin->version = 2015082400;
	$plugin->component = 'block_evalcomix';
?>

Muchas gracias por el trabajo realizado y esta gran utilidad para la evaluación en moodle.
Un saludo.

**Comment by evalfor** [comment]
Muchas gracias por la aportación ;) 
Un saludo.
