### ISSUE TITLE
classes and functions must be namespaced or prefixed with plugin name.

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#13]
All local functions must be prefixed with the plugin name - eg these function names are incorrect:
function get_activity_data
function add_date_time_selector
function get_evalcomix_activity_data

Correct examples would be:
function block_evalcomix_get_activity_data
function block_evalcomix_add_date_time_selector
function block_evalcomix_get_evalcomix_activity_data

This is the same for class names - which much be namespaced within block_evalcomix or prefixed with the plugin name.

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
