### ISSUE TITLE
invalid use of sql.

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#16]
variables must never be included in inline sql - you must pass all variables as parameters into the Moodle db functions.
Eg:
https://github.com/evalfor/moodle-block_evalcomix/blob/master/assessment/undone_evx.php#L29
```
 $sql2 = "SELECT id, finalgrade FROM " . $CFG->prefix . "grade_grades_history
                WHERE userid=$userid AND itemid=".$grade->grade_item->id." AND source like 'mod/%'
                ORDER BY id DESC";
    $gradeevalcomix2 = $DB->get_records_sql($sql2);
```
Should be:
```
 $sql2 = "SELECT id, finalgrade FROM {grade_grades_history}
                WHERE userid= ? AND itemid= ? AND source like 'mod/%'
                ORDER BY id DESC";
    $gradeevalcomix2 = $DB->get_records_sql($sql2, array($userid, $grade->grade_item->id));
```
Note - I have also removed $CFG->prefix and replaced with curly braces around the table name.

Please review all sql in your code and tidy up the use of $CFG->prefix and use correct paramater handling.

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
