### ISSUE TITLE
thirdpartylibs.xml is required when you include 3rd party libs

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#17]
Hopefully you'll remove some of these and use the core libs (eg jquery) but if you still have others that are required like the google.js one you have added you must also include a thirdpartylibs.xml file in your code that describes the lib and provides details on the licence associated with the file.

more info on this here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
