### ISSUE TITLE
classes/functions and constants do not follow naming conventions

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#18]
Please see:
https://docs.moodle.org/dev/Coding_style#Naming_Conventions

classes like "curly", constants like "DISPLAY_TOOL" do not follow the guidelines and can interfere with core code.
Please see here for more info:
https://docs.moodle.org/dev/Coding_style#Naming_Conventions

This is a definite blocker for approval in the plugins db.

It's also much easier if you put your classes into a classes folder rather than in various other locations.

**Comment by danmarsden** [comment]
another example:
class calculator_average
should be named block_evalcomix_calculator_average - or namespaced within the classes folder.

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
