### ISSUE TITLE
custom forms with no sesskey handling

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#22]
When you implement your own custom forms that implement actions - delete/insert/update etc - you need to check the sesskey manually to prevent csrf.
more info here:
https://docs.moodle.org/dev/Security:Cross-site_request_forgery

but - ideally you would be moving a lot of those custom forms to using moodle's forms lib.

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
