### ISSUE TITLE
incorrect definition of settings - polluting global $CFG

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#7]
plugins should be using the config_plugins table instead of the main config table.

To do this you need to replace stuff like this:
$settings->add(new admin_setting_configtext('evalcomix_serverurl'

with:
$settings->add(new admin_setting_configtext('block_evalcomix/serverurl'

and then use something like:
$config = get_config('block_evalcomix');
$config->serverurl;

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
