### ISSUE TITLE
inconsistent capability checks

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#8]
in some of your files, the capabilty check is buried down the bottom of the file - eg /assessment/assessment_form.php you check the value of the var $viewtemplate, but if it doesn't == 0 or 1 then no capability check is performed.

in /assessment/assigning_users_form.php you make multiple unncessary "require_login() calls 

in configuration.php you seem to perform hide/show actions before a login or capability check, potentially allowing un-authenticated users to make changes to course module tables.

Please review all files and make sure appropriate login and capability checks are performed at the top of the page.

**Comment by danmarsden** [comment]
another good example of some code you need to review is: download_preview.php - a check for login is made, but you can pass a number of params that could allow a student to download another students information.

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
