### ISSUE TITLE
invalid wrappers for db functions

### ISSUE THREAD

**Issue by danmarsden** [evalfor/moodle-block_evalcomix#9]
For example: evalcomix_tasks::update() and evalcomix_tasks::exist are wrappers for core db functions - you shouldn't be wrapping these functions like this and should be calling them directly in the code - this makes your code very hard to review. Is there a reason you are wrapping the code instead of calling the db functions directly?

**Comment by evalfor** [comment]
Done.
Thanks for the contribution.
